name: Run regression

env:
  PROJECT_DIR: ${{ env.GITHUB_WORKSPACE }}
  VERIF_DIR: ${{ env.PROJECT_DIR }}/sw/verif
  SIM_DIR: ${{ env.PROJECT_DIR }}/sim/rtl_sim

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: llvm

    - name: Build test benches
      run: |
        cd $SIM_DIR
        make -f Makefile.ghdl
