name: Run regression

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_DIR: ${{ env.GITHUB_WORKSPACE }}
      VERIF_DIR: ${{ env.GITHUB_WORKSPACE }}/sw/verif
      SIM_DIR: ${{ env.GITHUB_WORKSPACE }}/sim/rtl_sim

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: ghdl/setup-ghdl-ci@nightly
      with:
        backend: llvm

    - name: Build test benches
      run: |
        cd $SIM_DIR
        make -f Makefile.ghdl
